name: Link Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --accept 200,206,429
            --timeout 20
            --max-retries 2
            --exclude-mail
            "./**/*.md"
            "./**/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
